// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqelkutlhhxwcqwjwvjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxZWxrdXRsaGh4d2Nxd2p3dmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjU2MDQsImV4cCI6MjA2NDE0MTYwNH0.X1re8XJ06oq3vKoCGpghRaNHHAaEGo42F9F_kk-pBcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);